### ISSUE TITLE
Problem with build

### ISSUE THREAD

**Issue by armaos** [stripe/log4j-remediation-tools#5]
Hello and thanks for sharing this tool! My apologies if i ask newbie things, but i have been worried about the log4j issue.

I am on an AWS instance
`NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"`

`$uname -a`
`Linux ip-172-31-89-223.ec2.internal 4.14.225-169.362.amzn2.x86_64 #1 SMP Mon Mar 22 20:14:50 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

I have installed golang
`sudo yum install golang -y`
`$ go version`
`go version go1.15.14 linux/amd64
`

from the `find-vulnerabilities` folder I run
`env GOOS=linux GOARCH=amd64 go build -o log4j-finder-amd64-linux *.go`
but I get
`helpers.go:7:2: package io/fs is not in GOROOT (/usr/lib/golang/src/io/fs)`

Do I do something wrong?

Thank you so much!
Alex

**Comment by mironov-stripe** [comment]
Hey @armaos,

`io/fs` package comes from standard library and requires go v1.16 and higher: https://pkg.go.dev/io/fs@go1.16.7?tab=versions 
According to the log you pasted you got `1.15.14` installed by yum.

**Comment by armaos** [comment]
thank you so much. solved.
